######
##
# 1) start: docker-compose up -d
# 2) run asr: docker exec kamose asr --help
# 3) check http://localhost:8080 and http://localhost:5000 and http://localhost:5000/shutdown
##
######
version: '2.3'

networks:
  anet:

services:

  # BEGIN: kaldi-model-server
  kamose:
    image: uhhlt/kaldi-model-server:latest
    container_name: kamose
    volumes:
      - ${PWD}/models:/projects/kaldi-model-server/models
    ports:
      - 5000:5000
    networks:
      - anet
    working_dir: /projects/kaldi-model-server/
    devices:
      - /dev/snd:/dev/snd
  # END: kaldi-model-server

  # BEGIN: FRONTEND
  frontend:
    image: bigabig/mbot-frontend:latest
    ports:
      - 8080:8080
    networks:
      - anet
  # END: FRONTEND

  # BEGIN: KEYWORDS
  keywords:
    image: bigabig/mbot-keyterms:latest
    ports:
      - 8888:8080
    networks:
      - anet
  # END: KEYWORDS

  # BEGIN: NER
  ner:
    image: bigabig/mbot-ner:latest
    ports:
      - 9000:9000
    networks:
      - anet
  # END: NER

  # BEGIN: TEXTRANK
  textrank:
    image: bigabig/mbot-textrank:latest
    ports:
      - 9001:5000
    networks:
      - anet
  # END: TEXTRANK
